server:
  port: 8083

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: localhost
    port: 1025
    username: maildev
    password: maildev
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html