version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "9098:8080"
    command: [ "start-dev", "--import-realm" ]

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # AMQP Port

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:80"   # MailDev UI
      - "1025:1025" # SMTP Server

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres-user-service:
    image: postgres:15
    container_name: postgres-user-service
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
    ports:
      - "5432:5432"

  postgres-demo-service:
    image: postgres:15
    container_name: postgres-demo-service
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_service
      POSTGRES_PASSWORD: demo_service
    ports:
      - "5434:5432"
