server:
  port: 8123

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
#          uri: http://user-serv:8081
          predicates:
            - Path=/api/users/**

        - id: demo-service
          uri: lb://demo-service
#          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: notification-service
          uri: lb://notification-service
#          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**

keycloak:
  jwk-uri: "http://localhost:9098/realms/demo-realm/protocol/openid-connect/certs"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
